### ISSUE TITLE
Fix Responsive issues of OdeToCode 

### ISSUE THREAD

**Issue by Nishchayverma** [dscbvppune/dscbvppune.github.io#6]
Below 991px breakpoint, the FAQs accordion does not work.
Come up with a solution to fix this.

**Comment by shivamtandon200500** [comment]
According to me, navbar collapse classes and accordion collapse classes are clashing to each other.
As in the breakpoint below 991px ,you guys have disabled collapse feature in navbar hence its vertical accordion collapse feature is also disabled.(Maybe the Universal Class will be clashing).

**Comment by Nishchayverma** [comment]
@toHarsh Check if we have disabled any navbar collapse class cause I do not think so , because we have not used navbar collapse functionality at all anywhere in code . As far as OdeToCode page is concerned there is no such clash in classes .

**Comment by toHarsh** [comment]
@Nishchayverma No, there is no 'navbar-collapse' class in the home-page.

**Comment by greenorb007** [comment]
@toHarsh , if you have solved the problem locally please go ahead and create a fix for it and add a PR.

**Comment by codetronaut** [comment]
@toHarsh , if you have figured out the problem please go ahead and create a PR for this, (and please test the patch before sending a PR, locally).

**Comment by shivamtandon200500** [comment]
@Nishchayverma 
![Screenshot (228)](https://user-images.githubusercontent.com/57308704/98834374-240c1300-2465-11eb-84db-abdc8c6b66b8.png)


I have noticed that you guys have created a horizontal slider for large screens and a separate section for small screens like mobile. Also, there is a class herosection in which accordion function is written.
This accordion heresection function is common for both faq and horizontal accordion. According to me , in HeroSection.module.css line number 145 ,when you hide this herosection then maybe the "faq" accordion also stops working.
        But when I have displayed this herosection, it works properly but CSS is lost. Also I have made another faq section and I have hide the previous faq accordion still it's not working.
        Hence, I am on conclusion that this "herosection" part has some glitch.

**Comment by codetronaut** [comment]
@Nishchayverma, please have a look at it.

**Comment by Nishchayverma** [comment]
The toggleAccordian function in the above Screenshot is used ONLY for opening and closing of the nav items ie, Team , about ,faq not for the "FAQ" accordian  . As you have mentioned if we display the laptop as well mobile hero-section then the FAQ accordian of laptop view is working but the mobile one is still not working , so i guess problem lies with CSS of mobile view accordian FAQ section . Thanks for the input , i will inform when the issue is solved

**Comment by Nishchayverma** [comment]
Ok so this issue was caused due to repetition of id attribute because the DOM was being repeated for laptop as well as mobile version . To rectify this, simply use classname instead of id in the bootstrap accordian.
